### ISSUE TITLE
V2ray free proxy list (realtime vmess checker / aggregator)

### ISSUE THREAD

**Issue by rabbityear** [net4people/bbs#200]
Sharing this v2ray free proxy aggregator I found on Reddit: https://vpn.fail/free-proxy/type/v2ray

It is super helpful to find new vmess open proxy servers.

The list is updated in realtime every few minutes.

Rabbit

**Comment by rabbityear** [comment]
Bulk txt output for v2ray proxy list: https://vpn.fail/free-proxy/v2ray

<img width="830" alt="vpn.fail_free-proxy_v2ray" src="https://user-images.githubusercontent.com/123699423/214967681-846ca11a-01c3-41d0-bbee-619aaece7611.png">

**Comment by wkrp** [comment]
If the proxy addresses are listed publicly, won't they be easy to block?

I appreciate your post, but this is not a place to post proxy lists. The trouble is that users don't have a way to know whether the proxies and their operators are trustworthy. So if you don't mind, I'll close this thread.

**Comment by rabbityear** [comment]
If they are easy to block (because being public) it doesn't mean they actually are blocked. Also depends what country does the blocking, how fast they are etc.

I had success finding working vmess using this list for both Iran and China friends, especially recommend looking for Cloudflare hosted v2ray. But hoping to help was why I post, if you think better close the thread no problem!

**Comment by wkrp** [comment]
Yeah I'm not mad. Here we focus on research and development, but I know end users are also looking for hints to get connected. I just don't want to give people the impression that a list of proxies is trustworthy just because it is posted here.
