### ISSUE TITLE
how http custom files created?

### ISSUE THREAD

**Issue by 3245** [net4people/bbs#233]
hello
i have some public .hc files works with http custom app in android and never banned
how this files configured? there is any tutorial for config this on server side?

Thanks for your helps.

**Comment by 3245** [comment]
> @3245, this forum is aimed at researchers and developers, not for help using or configuring a circumvention system.
> 
> If you find that the HTTP Custom app ([this one](https://play.google.com/store/apps/details?id=xyz.easypro.httpcustom), I suppose) works where other systems do not work, that is useful information for developers and would be on topic. But we will need some actionable information: at least what country you are in, and ideally also what settings you are using in the app.
> 
> If you just need help using the app, this is not the place.

iran...
i not have problem with app, i want know how to configure server side

**Comment by wkrp** [comment]
> i not have problem with app, i want know how to configure server side

This is not the place for that discussion. You will have to ask somewhere else.
