### ISSUE TITLE
Is TLS fragment available in China? 

### ISSUE THREAD

**Issue by louiesun** [net4people/bbs#370]
I haven't use GFW-knocker's [project](https://github.com/GFW-knocker/gfw_resist_tls_proxy) successfully since it even can't wrong without fragment. (max fragment size 1000). (I test with a website available in China). 

In addition, Cloudflare returns 400 Bad Request.

**Comment by maoist2009** [comment]
> this was mainly written for iran, where it still works pretty well as an all-purpose way to "freshen up" existing tunnels without changing the server. I saw that some chinese devs use fragmentation _while testing_ the GFW, but am not aware of it being widely deployed there.
> 
> significant parts of this are now merged into xray's [freedom outbound](https://xtls.github.io/en/config/outbounds/freedom.html#outboundconfigurationobject) and there exist semi-private forks of xray developing it a bit further.
> 
> I think max fragment size=1000 is a bit high and unlikely to split up the packets where you need them.

I guess it works for the most places of china. But unluckily, I am in Shanghai. It is said that the GFW of Shanghai, Beijing, Guangzhou will maintain a connection of tcp. So it seems that fragment won't work. 

[This](https://github.com/maoist2009/TlsFragment) is my test code:

**Comment by louiesun** [comment]
notice the differences between tls frag and tcp frag!

**Comment by wkrp** [comment]
I'll reopen the issue to preserve the discussion.
