### ISSUE TITLE
Nadi Group Foam

### ISSUE THREAD

**Issue by nasserahmadi** [net4people/bbs#397]
About Nadi Group
I am Musavi, the commercial manager of Nadi Group & Karavar company
Nadi Group ( 1994 ) , based in Tehran & Karaj , Iran, is a distinguished name in the design and manufacturing of decorative arts and foam-based products. With a focus on innovation and quality, Nadi Group offers a diverse range of services, from conceptual art design to the production of interior decorations.
Specializing in creating intricate metal and foam decorations, Nadi Group also excels in designing and fabricating historical costumes and props for films, events, and celebrations. The company’s expertise in foam work extends to the crafting of unique children's playhouses, recreational equipment, and soft play structures, emphasizing durability, safety, and creativity.
Duties of Nadi group: design and manufacture of decorative arts, design and manufacture
Products made from foam
The foam products engineered by Nadi Group are recognized for their lightness, resistance, and waterproof qualities, making them ideal for various applications. Additionally, Nadi Group has pioneered a device for cleaning the facades of towers without requiring human intervention, showcasing the company’s commitment to practical and innovative solutions.

With respect
Musavi
Commercial manager
Tel: 0098-21-44631215  ,  0098-26-32760572
Email : nadigroup.karavar@gmail.com
Address: 1 - No. 3 - Block 19 - Ekbatan-Tehran-Iran.
                 2 -  No. 6 - Sahel - Farhangian St. - Valfajr - Mehrvila - Karaj - Iran.
Post Cod : 31336-58318

![IMG_20240721_130228_399](https://github.com/user-attachments/assets/e3023ae6-38b1-421b-8599-db2650feaffb)
![IMG-20240711-WA0003](https://github.com/user-attachments/assets/b0328662-9ed4-436a-825a-c5686e506aee)
![Uploading IMG-20240620-WA0033.jpg…]()
![Uploading IMG-20240711-WA0014.jpg…]()

**Comment by nasserahmadi** [comment]
![IMG-20240711-WA0014](https://github.com/user-attachments/assets/4140566c-1c4f-44be-a2bc-16abd99cc78b)

**Comment by showgood163** [comment]
@wkrp 

This is a spam post.
