### ISSUE TITLE
xx.network a blockchain privacy chain using cmixx mixnet

### ISSUE THREAD

**Issue by TheWanderer1983** [net4people/bbs#399]
**What is xx.network:** 
Founded by  [David Chaum](https://en.wikipedia.org/wiki/David_Chaum), the XX Network fundamentally comprises both a quantum-resistant blockchain and unique mix network (cmixx). Also provides metadata protection.

It has been live in mainnet since 2021 and development continues across many teams, coordinated by a Foundation.
[xx.network](https://xx.network/)

Mixing is done with [cmixx](https://patcrypt.com/what-is-cmixx-is-it-different-from-cmix/)
[cmix paper](https://eprint.iacr.org/2016/008.pdf)

**Comment by wkrp** [comment]
Please say more about how the XX Network is relevant from the point of view of censorship. A blockchain or mixnet is not inherently blocking-resistant. Does the XX Network do anything interesting to prevent blocking of communication between its mixnodes, for example?

From what I am able to find in a web search, it seems that the XX Network and [XX Messenger](https://en.wikipedia.org/wiki/Xx_messenger), if anything, may fit into the class of censorship-resistant *publishing* platforms; that is, it's hard for the platform itself to delete or filter messages. But that is not the same thing as access *to* the platform being difficult to block.

**Comment by TheWanderer1983** [comment]
>Does the XX Network do anything interesting to prevent blocking of communication between its mixnodes, for example?

The xx network runs on top of the substrate blockchain network. These nodes run cmixx which require them to be able to participate in the network.  The idea is to function like TOR overlay network but over blockchain nodes. 
>Please say more about how the XX Network is relevant from the point of view of censorship. A blockchain or mixnet is not inherently blocking-resistant

Correct, this network should be considered more like a TOR overlay network. It still requires the usual methods to gain access  in restrictive countries.  I mentioned it due to some of it features that improve on TOR in regards to traffic analysis, and it's metadata protection. 

>From what I am able to find in a web search, it seems that the XX Network and [XX Messenger](https://en.wikipedia.org/wiki/Xx_messenger),

There have been some developments since. xx messenger is now replaced with [Haven](https://haven.xx.network/) which runs in a web browser, and [Phoenixx](https://phoenixx.io/). However, it should be mentioned they have developed a SDK so others can develop their own censorship resistance apps to integrate with the network.

**Comment by wkrp** [comment]
Okay. I will close this thread as I don't think it is quite on topic.

> they have developed a SDK so others can develop their own censorship resistance apps to integrate with the network.

However, if they have developed an interface to connect with obfuscation modules (like pluggable transports), or if someone is working on that, then discussing that would be on topic.
