### ISSUE TITLE
求助client hello标准 / help with client hello standard

### ISSUE THREAD

**Issue by louiesun** [net4people/bbs#403]
见此https://github.com/URenko/Accesser/discussions/201#discussion-7275050

*See here: https://github.com/URenko/Accesser/discussions/201#discussion-7275050*

**Comment by wkrp** [comment]
@louiesun Do you have a specific question to ask? The linked discussion seems to be about how fragmentation of TLS handshakes sometimes succeeds against the GFW, despite the GFW's ability to reassemble TCP streams. But I do not understand what, specifically, you are asking about.

**Comment by louiesun** [comment]
So notice! 
There are two kinds of frag. 
one simply frag the clinet hello to several pieces on tcp layer. 
but infact, tls layer supports frag, it make fata into pieces and add a head to each of them. 

In china, gfw assigns the tcp frag and rst, but it doesn't assign tls frag.

**Comment by wkrp** [comment]
Yes! You are correct. Here is a thread that touches on the difference between TCP and TLS fragmentation: #308.

> This blog post explores an interesting idea: fragmenting TLS messages (especially Client Hello) over multiple TLS records. This is different from TCP segmentation, which has been studied in the past by, e.g., [Winter & Lindskog 2012](https://censorbib.nymity.ch/#Winter2012a) (Section 5.2, [brdgrd](https://github.com/NullHypothesis/brdgrd)), [Khattak et al. 2013](https://censorbib.nymity.ch/#Khattak2013a), and [Bock et al. 2021](https://censorbib.nymity.ch/#Bock2021c) (Section 4.1), and is implemented in tools including [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI#active-dpi). Rather, this research takes advantage of the fact that TLS [*messages*](https://www.rfc-editor.org/rfc/rfc5246#section-6) (e.g. Client Hello) are carried in TLS [*records*](https://www.rfc-editor.org/rfc/rfc5246#section-6.2), and that one message may be [fragmented](https://www.rfc-editor.org/rfc/rfc5246#section-6.2.1) over multiple records.
