### ISSUE TITLE
Proton VPN绕过封锁的方式让我挺感慨的 The way Proton VPN bypasses the blockade makes me quite emotional.

### ISSUE THREAD

**Issue by ghost** [net4people/bbs#427]
我自己也很好奇为什么这家VPN从2024年年初开始恢复了在中国的工作，没想到听他们的开发者分析了一番，竟然用到了如此巧妙的方式，我把他们的原话翻译成汉语发上来，分享给大家：

> ProtonVPN 在一些网络严格受限的地方依然可以正常工作，这是因为其采用了一套巧妙的机制。整个流程可以分为两部分：
> 
> 1. 确保客户端可以正常访问 API 端点  
> 2. 确保客户端可以连接到 VPN 服务器
> 
> 
> 一、API 端点的访问策略
> 为了让客户端能够正常工作，ProtonVPN 首先需要解决如何访问 API 端点的问题。流程如下：
> 
> 1. 尝试通过 HTTPS 直接访问 API 端点
>    - 客户端首先以 HTTPS 协议访问默认的 API 端点，尝试解析一个特定的 DNS 记录用于获取备用API端点地址。
>    - 如果访问 成功，客户端会直接与主 API 端点通信，不再进行其他操作。并放弃上一步查询到的结果。
>    - 如果访问 失败，则执行下一步。
> 
> 2. 调用内置的 DoH 服务
>    - 如果直接访问失败，客户端会切换到内置的两个 DoH（DNS over HTTPS）服务：Quad9 和 Google。
>    - 通过 DoH 查询特定的 DNS 记录，以获取备用 API 服务器地址。
>    - 使用获取到的 IP 地址直接访问：
>      - 如果 成功，客户端会与备用 API 端点继续通信。
>      - 如果 失败且错误非连接超时，放弃连接。
>      - 如果 失败且错误为超时，进入下一步。
>    - 如果 DoH 服务都无法连接，则直接进入下一步
> 
> 3. 启动临时 VPN 模块
>    - 如果通过内置的 DoH 服务依然无法获取备用地址，客户端会启动一下设备上的 VPN 模块。
>    - 临时 VPN 模块尝试连接到 Proton 的已知服务器，建立通信后再次请求 API 端点。
>    - 请求完成后关闭 VPN，客户端切换到备用 API 地址继续通信。
> 
> 如果以上方法仍然失败，客户端会继续轮询备用 API 地址，直到成功为止。
> 
> 
> 二、VPN 服务器的连接策略
> 当客户端成功访问 API 后，接下来的目标是连接到 ProtonVPN 的服务器。  
> 为此，ProtonVPN 使用了名为 Stealth 协议 的技术，这是一种经过精心设计的混淆协议。
> 
> 1. Stealth 协议的技术核心
>    - Stealth 协议的本质是 混淆后的 WireGuard over TLS 隧道。
>      - 在 WireGuard 的基础上增加了一层 TLS 加密。
>    - 外层的 TLS 层可以模仿标准 HTTPS 流量：
>      - 使用 OpenSSL 库来实现TLS连接。
>      - 通过 JA3 指纹的伪造，使客户端发出的流量伪装成常见的的 HTTPS 应用。
>    - 服务端也保持相同的伪装技术（也使用openssl库实现TLS连接和JA3S指纹的伪造），使流量难以被检测和追踪。
> 
> 2. 连接流程
>    - 客户端随机选择一个或者由用户指定一个已存在的 VPN 服务器。
>    - 使用 Stealth 协议发起连接，混淆流量以避开网络审查。
>    - 如果当前服务器连接失败，客户端会自动尝试其他服务器，直到成功为止。
> 
> 在这两种技术的确保下，终于实现了较高的可靠性。

-----------------------------------------------

Actually, I am also very curious about why this VPN is available in China again since the beginning of 2024. I didn’t expect that after listening to their developers’ analysis, they actually used such a clever method. I posted their original words to here and shared them with everyone:

> Why can ProtonVPN still work properly in some places with strictly restricted networks? This is because it uses a clever mechanism.
> The whole process can be divided into two parts:
> 
> 1. Make sure the client can access the API endpoint normally
> 
> 2. Make sure the client can connect to the VPN server
> 
> I. Access strategy for API endpoints
> In order for the client to work properly, ProtonVPN first needs to solve the problem of how to access the API endpoint. The process is as follows:
> 
> 1. Try to access the API endpoint directly via HTTPS
> - The client first accesses the main API endpoint with the HTTPS protocol and tries to resolve a specific DNS record to obtain the address of the backup API endpoint.
> - If the access is successful, the client will communicate directly with the main API endpoint and no longer perform other operations. And abandon the results of the previous DNS query.
> - If the access fails, proceed to the next step.
> 
> 2. Call the built-in DoH service
> - If direct access fails, the client will switch to the two built-in DoH (DNS over HTTPS) services: Quad9 and Google.
> - Query a specific DNS record through DoH to obtain the address of the backup API server.
> - Direct access using the obtained IP address:
> - If successful, the client will continue to communicate with the backup API endpoint.
> - If failed and the error is not a connection timeout, abandon the connection.
> - If failed and the error is a timeout, go to the next step.
> - If none of the DoH services can connect, go directly to the next step
> 
> 3. Temporary Start VPN module on user device.
> - If the backup address still cannot be obtained through the built-in DoH service, the client will temporarily start the VPN module on the device.
> - Then try to connect to Proton's known VPN servers, and after establishing communication, request the API endpoint again.
> - After the request is completed, turn off the VPN, and the client switches to the backup API address to continue communication.
> 
> If the above method still fails, the client will continue to poll all available API addresses until it succeeds.
> 
> 2. VPN server connection strategy
> After the client successfully accesses the API, the next goal is to connect to ProtonVPN's server.
> To this end, ProtonVPN uses a technology called Stealth Protocol, which is a carefully designed obfuscation protocol.
> 
> 1. Technical core of Stealth protocol
> - The essence of Stealth protocol is obfuscated WireGuard over TLS tunnel.
> - A layer of TLS encryption is added on top of WireGuard.
> - The outer TLS layer can imitate standard HTTPS traffic:
> - Use OpenSSL library to implement TLS connection.
> - By forging JA3 fingerprint, the traffic sent by the client is disguised as a common HTTPS application.
> - The server also maintains the same disguise technology (also uses openssl library to implement TLS connection and forge JA3S fingerprint), making the traffic difficult to detect and track.
> 
> 2. Connection process
> - The client randomly selects an existing VPN server or the user specifies an existing VPN server.
> - Use Stealth protocol to initiate a connection and obfuscate traffic to avoid network censorship.
> - If the current server connection fails, the client will automatically try other servers until it succeeds.
> 
> With the help of these two technologies, a high reliability is finally achieved.

**Comment by wkrp** [comment]
I had heard that Proton Stealth was WireGuard inside TLS. Besides protocol obfuscation, though, the other big difficulty is address blocking of the API endpoints. If I am reading what you posted correctly, Proton VPN tries multiple steps to reach the API servers:

1. Direct access. (Presumably HTTPS.)
2. Resolve the API server domain name using DoH. (Will work if the API server is only DNS-blocked, not SNI-blocked or IP-blocked.)
3. Turn on whatever other VPN the user may have installed, and try accessing the API server that way. (?) Not sure I understand that step correctly.
4. Keep trying known API servers until one succeeds.

I don't know, if it started working, as you say, perhaps Proton added additional API endpoints, or changed the IP address of some API endpoints, and they haven't been added to the GFW blocklist yet?
